"""
ScheduleTimelinesBuilder — FHIR eligibility Group relativeTime windows -> USDM
StudyDesign.scheduleTimelines.

Priority 64 — runs right after StudyCellsBuilder (63) so it can read
'version.studyDesign.arms' from the context bag: the Main Timeline scaffold
below reuses SCREENING_EPOCH_ID/TREATMENT_EPOCH_ID from EpochsBuilder, which
only creates those epochs when there is at least one arm — same gate reused
here so the scaffold never points at epoch ids that don't exist.

Mirrors readi_core ScheduleTimelinesSectionBuilder.php (priority 33 there —
no cross-builder dependency on readi's side because its epochs are always
created unconditionally), adapted to FHIR as the data source instead of
readi's internal Timing entities:

  • Main Timeline — always the same 2-instance scaffold (Screening1 ->
    Treatment1, epochId StudyEpoch_1/StudyEpoch_2) readi_core hardcodes in
    ArmsSectionBuilder.php; no FHIR field drives it. One Timing ("FU_DUR",
    Fixed Reference, P0D) — readi's $targetDuration source isn't extracted
    from FHIR anywhere yet, so it always falls back to the same 'P0D' /
    "Planned duration is not specified" defaults transformStringTiming(null)
    and PlannedDurationUsdmModel's own defaults produce in readi_core.

  • History Timeline — one instance+Timing pair per DISTINCT
    (offsetRange.low, offsetRange.high) day-pair found across every
    characteristic[].relativeTime.offsetRange in the contained Groups (all of
    them — the top "eligibility-criteria" Group as well as every Group it
    valueReferences into), chained sequentially via defaultConditionId and
    ending in a synthetic SCR instance (Fixed Reference, self-referencing
    P0D) — mirrors resolveHistoryEntries()'s non-empty branch. When no
    relativeTime window is found anywhere, falls back to the same
    MIN120Y+SCR default pair resolveHistoryEntries() returns for its empty
    branch.

Inversion formula (see app/config/mappings/13_eligibility_group.yaml, the
"Group low/high timing range" rows, for the forward direction being
reversed here):
    forward BEFORE (C201357):  low = -(value+windowLower)   high = -value+windowUpper
    forward AFTER  (C201356):  low =   value-windowLower     high =  value+windowUpper
We fix windowLower = P0D — the same convention readi_core's own MIN120Y
default already uses (confirmed against the real "MIN120Y"/"P4W" windows in
Input/NCT01750580_limited_tagged_resp.json and Output/MyNewFile.json, both
generated by this project's own forward direction) — which collapses both
cases to one invertible pair:
    value       = |low| days
    windowUpper = (high - low) days
    type        = BEFORE if low < 0 else AFTER
This is lossy on the human-authored unit (everything round-trips through
days) and on any originally-nonzero windowLower — an accepted limitation,
consistent with the rest of this reverse-direction codebase.
"""

from __future__ import annotations

from app.services.usdm_from_fhir.base_builder import AbstractSectionBuilder
from app.services.usdm_from_fhir.context import UsdmBuildContext
from app.services.usdm_from_fhir.builders.study_design.epochs_builder import (
    SCREENING_EPOCH_ID,
    TREATMENT_EPOCH_ID,
)

_START_TO_START = ("C201355", "Start to Start")
_BEFORE = ("C201357", "Before")
_AFTER = ("C201356", "After")
_FIXED_REFERENCE = ("C201358", "Fixed Reference")

_MAIN_TIMELINE_ID = "ScheduleTimeline_Main"
_MAIN_INSTANCE_1 = "ScheduledActivityInstance_1"
_MAIN_INSTANCE_2 = "ScheduledActivityInstance_2"
_MAIN_EXIT_ID = "ScheduleTimelineExit_Main"

_HISTORY_TIMELINE_ID = "ScheduleTimeline_History"
_HISTORY_EXIT_ID = "ScheduleTimelineExit_History"
_HISTORY_INSTANCE_1 = "HistoryInstance_1"
_SCR_INSTANCE_ID = "HistoryInstance_SCR"


class ScheduleTimelinesBuilder(AbstractSectionBuilder):

    def get_key(self) -> str:
        return "version.studyDesign.scheduleTimelines"

    def get_priority(self) -> int:
        return 64

    def build(self, context: UsdmBuildContext) -> list:
        timelines: list[dict] = []

        main_timeline = self._build_main_timeline(context)
        if main_timeline is not None:
            timelines.append(main_timeline)

        timelines.append(self._build_history_timeline(context))
        return timelines

    # ------------------------------------------------------------------
    # Main Timeline — fixed Screening -> Treatment scaffold
    # ------------------------------------------------------------------

    def _build_main_timeline(self, context: UsdmBuildContext) -> dict | None:
        arms: list = context.get("version.studyDesign.arms") or []
        if not arms:
            return None

        instances = [
            self._instance(
                _MAIN_INSTANCE_1, "Screening1", "Screening",
                epoch_id=SCREENING_EPOCH_ID, default_condition_id=_MAIN_INSTANCE_2,
            ),
            self._instance(
                _MAIN_INSTANCE_2, "Treatment1", "Treatment",
                epoch_id=TREATMENT_EPOCH_ID, timeline_exit_id=_MAIN_EXIT_ID,
            ),
        ]

        timing = self._timing(
            context, timing_id="Timing_FU_DUR", name="FU_DUR",
            type_code=_FIXED_REFERENCE, value="P0D",
            from_instance=_MAIN_INSTANCE_2, to_instance=_MAIN_INSTANCE_2,
            value_label="Screening index",
        )

        return {
            "id": _MAIN_TIMELINE_ID,
            "extensionAttributes": [],
            "name": "Main Timeline",
            "label": "Main Timeline",
            "description": "",
            "mainTimeline": True,
            "entryCondition": "",
            "entryId": _MAIN_INSTANCE_1,
            "exits": [self._exit(_MAIN_EXIT_ID)],
            "timings": [timing],
            "instances": instances,
            "plannedDuration": {
                "id": "PlannedDuration_1",
                "extensionAttributes": [],
                "text": "Planned duration is not specified",
                "quantity": None,
                "durationWillVary": True,
                "reasonDurationWillVary": "Duration is missing",
                "instanceType": "Duration",
            },
            "instanceType": "ScheduleTimeline",
        }

    # ------------------------------------------------------------------
    # History Timeline — reconstructed from eligibility relativeTime windows
    # ------------------------------------------------------------------

    def _build_history_timeline(self, context: UsdmBuildContext) -> dict:
        windows = self._collect_relative_time_windows(context.fhir)

        instances: list[dict] = []
        timings: list[dict] = []

        if not windows:
            entry_id = _HISTORY_INSTANCE_1
            instances.append(self._instance(
                _HISTORY_INSTANCE_1, "MIN120Y", "MIN120Y",
                default_condition_id=_SCR_INSTANCE_ID,
            ))
            timings.append(self._timing(
                context, timing_id="Timing_MIN120Y", name="TMIN120Y",
                type_code=_BEFORE, value="P120Y",
                from_instance=_HISTORY_INSTANCE_1, to_instance=_SCR_INSTANCE_ID,
                window_lower="P0D", window_upper="P120Y",
                window_label="within last 120 years", value_label="Screening index",
            ))
        else:
            entries = []
            for idx, (low, high) in enumerate(windows, start=1):
                entries.append({"id": f"HistoryInstance_{idx}", "low": low, "high": high})

            entry_id = entries[0]["id"]
            for i, entry in enumerate(entries):
                next_id = entries[i + 1]["id"] if i + 1 < len(entries) else _SCR_INSTANCE_ID
                is_before = entry["low"] < 0
                n_days = abs(entry["low"])
                value_iso, short_label = self._pretty(n_days)
                upper_iso, _ = self._pretty(entry["high"] - entry["low"])
                name = f"{'MIN' if is_before else 'PLUS'}{short_label}"
                direction = "before" if is_before else "after"

                instances.append(self._instance(
                    entry["id"], name, name, default_condition_id=next_id,
                ))
                timings.append(self._timing(
                    context, timing_id=f"Timing_{i + 1}", name=name,
                    type_code=_BEFORE if is_before else _AFTER, value=value_iso,
                    from_instance=entry["id"], to_instance=_SCR_INSTANCE_ID,
                    window_lower="P0D", window_upper=upper_iso,
                    window_label=f"within {short_label} {direction} screening",
                    value_label=f"{short_label} {direction} screening index",
                ))

        instances.append(self._instance(
            _SCR_INSTANCE_ID, "SCR", "SCR", timeline_exit_id=_HISTORY_EXIT_ID,
        ))
        timings.append(self._timing(
            context, timing_id="Timing_SCR", name="SCR",
            type_code=_FIXED_REFERENCE, value="P0D",
            from_instance=_SCR_INSTANCE_ID, to_instance=_SCR_INSTANCE_ID,
            value_label="Screening index",
        ))

        return {
            "id": _HISTORY_TIMELINE_ID,
            "extensionAttributes": [],
            "name": "HISTORY",
            "label": "History Timeline",
            "description": "Timing of periods of the patients history relative to screening enabling EHR record matching.",
            "mainTimeline": False,
            "entryCondition": "Patient birth or entering the registration",
            "entryId": entry_id,
            "exits": [self._exit(_HISTORY_EXIT_ID)],
            "timings": timings,
            "instances": instances,
            "plannedDuration": None,
            "instanceType": "ScheduleTimeline",
        }

    # ------------------------------------------------------------------
    # FHIR extraction
    # ------------------------------------------------------------------

    @staticmethod
    def _collect_relative_time_windows(fhir_data: dict) -> list[tuple[int, int]]:
        """
        Every distinct (offsetRange.low.value, offsetRange.high.value) day pair
        found across characteristic[].relativeTime in every contained Group,
        in first-seen order. Scans all contained Groups unconditionally (the
        top "eligibility-criteria" Group and every Group it valueReferences
        into) rather than re-deriving the reference chain — relativeTime only
        ever appears on the leaf criterion characteristics, so a flat scan
        finds the same windows without depending on EligibilityCriteriaBuilder's
        or AbstractIndicationsBuilder's (different) traversal.
        """
        contained: list[dict] = fhir_data.get("contained") or []
        seen: dict[tuple[int, int], None] = {}

        for group in contained:
            if not isinstance(group, dict) or group.get("resourceType") != "Group":
                continue
            for ch in group.get("characteristic") or []:
                offset_range = ((ch.get("relativeTime") or {}).get("offsetRange")) or {}
                low = (offset_range.get("low") or {}).get("value")
                high = (offset_range.get("high") or {}).get("value")
                if low is None or high is None:
                    continue
                low, high = int(low), int(high)
                if low == 0 and high == 0:
                    continue  # "at screening" — already represented by the synthetic SCR instance
                seen.setdefault((low, high), None)

        return list(seen.keys())

    # ------------------------------------------------------------------
    # Small dict builders
    # ------------------------------------------------------------------

    @staticmethod
    def _pretty(days: int) -> tuple[str, str]:
        """(iso_duration, short_label) for a day count, e.g. (P120Y, 120Y)."""
        if days and days % 365 == 0:
            n, unit = days // 365, "Y"
        elif days and days % 7 == 0:
            n, unit = days // 7, "W"
        else:
            n, unit = days, "D"
        return f"P{n}{unit}", f"{n}{unit}"

    @staticmethod
    def _instance(
        instance_id: str, name: str, label: str, *,
        epoch_id: str = "", default_condition_id: str = "", timeline_exit_id: str = "",
    ) -> dict:
        return {
            "id": instance_id,
            "extensionAttributes": [],
            "name": name,
            "label": label,
            "epochId": epoch_id,
            "defaultConditionId": default_condition_id,
            "timelineExitId": timeline_exit_id,
            "activityIds": [],
            "instanceType": "ScheduledActivityInstance",
        }

    @staticmethod
    def _exit(exit_id: str) -> dict:
        return {"id": exit_id, "extensionAttributes": [], "instanceType": "ScheduleTimelineExit"}

    @staticmethod
    def _timing(
        context: UsdmBuildContext, *, timing_id: str, name: str,
        type_code: tuple[str, str], value: str, from_instance: str, to_instance: str,
        window_lower: str = "", window_upper: str = "", window_label: str = "",
        value_label: str = "", label: str = "",
    ) -> dict:
        return {
            "id": timing_id,
            "extensionAttributes": [],
            "name": name,
            "label": label,
            "description": "",
            "type": context.make_code(*type_code),
            "value": value,
            "valueLabel": value_label,
            "relativeToFrom": context.make_code(*_START_TO_START),
            "relativeFromScheduledInstanceId": from_instance,
            "relativeToScheduledInstanceId": to_instance,
            "windowLower": window_lower,
            "windowUpper": window_upper,
            "windowLabel": window_label,
            "instanceType": "Timing",
        }