"""
validate_usdm.py
----------------
CLI command that validates a USDM JSON file against the SDR conformance
validation service defined in .env (USDM_VALIDATION_APP_URL).

Usage examples
--------------
python -m app.command.validate_usdm
python -m app.command.validate_usdm --file Output/USDM_output.json
python -m app.command.validate_usdm --file Output/USDM_output.json --usdm-version 3
python -m app.command.validate_usdm --json
"""

import json
import os
import sys
from pathlib import Path

import click
import requests
from dotenv import load_dotenv
from rich.console import Console
from rich.table import Table
from rich import box
from rich.panel import Panel
from rich.text import Text

console = Console()

DEFAULT_INPUT_FILE = "Output/USDM_output.json"
DEFAULT_USDM_VERSION = "3"
ENV_FILE = ".env"


def _load_env() -> dict:
    """Load .env and return relevant config keys."""
    load_dotenv(dotenv_path=Path(ENV_FILE))
    return {
        "url": os.getenv("USDM_VALIDATION_APP_URL", "").strip("'\""),
        "version": os.getenv("USDM_VALIDATION_VERSION", DEFAULT_USDM_VERSION).strip("'\""),
    }


@click.command(
    name="validate-usdm",
    help=(
        "Validate a USDM JSON file against the SDR conformance validation service.\n\n"
        "Reads USDM_VALIDATION_APP_URL (and optionally USDM_VALIDATION_VERSION) from .env.\n\n"
        "The default input file is Output/USDM_output.json "
        "(generated by execute_example_fhir_to_usdm)."
    ),
)
@click.option(
    "--file", "-f",
    "input_file",
    default=DEFAULT_INPUT_FILE,
    show_default=True,
    help="Path to the USDM JSON file to validate.",
)
@click.option(
    "--usdm-version",
    "usdm_version",
    default=None,
    show_default=True,
    help=(
        "Value for the Usdmversion request header. "
        "Falls back to USDM_VALIDATION_VERSION in .env, then to '3'."
    ),
)
@click.option(
    "--json", "-j",
    "as_json",
    is_flag=True,
    default=False,
    help="Output as machine-readable JSON envelope.",
)
def validate_command(input_file: str, usdm_version: str | None, as_json: bool):
    # ---- Load .env config ----
    config = _load_env()

    url = config["url"]
    if not url:
        click.echo(
            "ERROR: USDM_VALIDATION_APP_URL is not set in .env", err=True
        )
        sys.exit(1)

    effective_version = usdm_version or config["version"]

    # ---- Load USDM file ----
    file_path = Path(input_file)
    if not file_path.exists():
        click.echo(f"ERROR: input file not found: {file_path}", err=True)
        sys.exit(1)

    with file_path.open(encoding="utf-8") as fh:
        try:
            usdm_data = json.load(fh)
        except json.JSONDecodeError as exc:
            click.echo(f"ERROR: invalid JSON in {file_path}: {exc}", err=True)
            sys.exit(1)

    # ---- POST to SDR validation service ----
    headers = {
        "Content-Type": "application/json",
        "Accept": "application/json",
        "Usdmversion": effective_version,
    }

    if not as_json:
        console.print()
        console.print(f"  [bold]Validating :[/bold] {file_path}")
        console.print(f"  [bold]URL        :[/bold] {url}")
        console.print(f"  [bold]Usdmversion:[/bold] {effective_version}")
        console.print()

    try:
        response = requests.post(url, json=usdm_data, headers=headers, timeout=60)
        status_code = response.status_code
        try:
            content = response.json()
        except Exception:
            content = {"raw": response.text}
    except requests.exceptions.RequestException as exc:
        payload = {
            "status": "error",
            "file": str(file_path),
            "url": url,
            "error_type": type(exc).__name__,
            "error_message": str(exc),
        }
        if as_json:
            click.echo(json.dumps(payload, indent=2, ensure_ascii=False))
        else:
            click.echo(f"[ERROR] Request failed: {exc}", err=True)
        sys.exit(1)

    # ---- Determine success ----
    issue_details = content.get("Issue_Details")
    success = isinstance(issue_details, list) and len(issue_details) == 0

    # ---- Output ----
    if as_json:
        output = {
            "status": "ok" if success else "invalid",
            "status_code": status_code,
            "file": str(file_path),
            "url": url,
            "usdm_version": effective_version,
            "success": success,
            "response": content,
        }
        click.echo(json.dumps(output, indent=2, ensure_ascii=False))
    else:
        # ---- Summary panel ----
        if success:
            summary_text = Text("✅  VALID — No conformance issues found", style="bold green")
        elif status_code >= 400:
            summary_text = Text(f"❌  ERROR — HTTP {status_code}", style="bold red")
        else:
            summary_text = Text(f"⚠️   INVALID — HTTP {status_code}", style="bold yellow")

        console.print(Panel(summary_text, expand=False))
        console.print()

        if issue_details is not None and len(issue_details) > 0:
            # Collect all unique keys across all issues for dynamic columns
            all_keys: list[str] = []
            for issue in issue_details:
                if isinstance(issue, dict):
                    for k in issue.keys():
                        if k not in all_keys:
                            all_keys.append(k)

            if all_keys:
                table = Table(
                    title=f"Conformance Issues ({len(issue_details)})",
                    box=box.ROUNDED,
                    show_lines=True,
                    highlight=True,
                    border_style="red",
                    header_style="bold magenta",
                )
                table.add_column("#", style="dim", width=4, justify="right")
                for key in all_keys:
                    table.add_column(key, overflow="fold")

                for i, issue in enumerate(issue_details, 1):
                    if isinstance(issue, dict):
                        row = [str(i)] + [str(issue.get(k, "")) for k in all_keys]
                    else:
                        row = [str(i), str(issue)] + [""] * (len(all_keys) - 1)
                    table.add_row(*row)

                console.print(table)
            else:
                # Issues are not dicts — just show them in a simple table
                table = Table(
                    title=f"Conformance Issues ({len(issue_details)})",
                    box=box.ROUNDED,
                    border_style="red",
                    header_style="bold magenta",
                )
                table.add_column("#", style="dim", width=4, justify="right")
                table.add_column("Issue", overflow="fold")
                for i, issue in enumerate(issue_details, 1):
                    table.add_row(str(i), json.dumps(issue, ensure_ascii=False))
                console.print(table)

        elif issue_details is not None and len(issue_details) == 0:
            console.print("  [green]No conformance issues found. 🎉[/green]")
        else:
            # Fallback: show full response as a key→value table
            table = Table(
                title="Response Body",
                box=box.ROUNDED,
                border_style="blue",
                header_style="bold cyan",
                show_lines=True,
            )
            table.add_column("Key", style="bold")
            table.add_column("Value", overflow="fold")
            for k, v in content.items():
                table.add_row(str(k), json.dumps(v, ensure_ascii=False) if not isinstance(v, str) else v)
            console.print(table)

        console.print()


if __name__ == "__main__":
    validate_command()

